### ISSUE TITLE
String data type

### ISSUE THREAD

**Issue by stesquality** [st-one-io/node-red-contrib-s7#94]
In Tia portal, I string data type in data block with address "P#DB1.DBX0.0". But in your detail it is written that "BDX" is for Boolean values. Could you please suggest me how can I use string values like text, etc.

**Comment by gfcittolin** [comment]
`P#`-like addresses are pointer addresses - that is, instead of the value itself, they contain the address where the actual value is stored. Right now the node does not support indirect/pointer addressing. One option to solve this is to program your PLC to copy the value you want to a known and fixed address, and then read from that address instead
