### ISSUE TITLE
Reading endpoint configuration from a text file

### ISSUE THREAD

**Issue by TommyBerz** [st-one-io/node-red-contrib-s7#96]
Hello I am trying to set the endpoint configuration throught the reading of a text file (stored in my PC) that contains the IP and the port useful for the endpoint configuration. I did the file reading and the recovery of the IP/port but I can't set them as endpoint connection parameters. It would be useful if you can read parameters directly from the payload, with that we could change endpoint configuration dynamically.

**Comment by gfcittolin** [comment]
Right now this is a bit out of sight for this node, because of the structural changes this would imply to the code and some edge cases that we'd need to sort out. Since, if you need dynamic endpoints you'll probably need dynamic variables too, doesn't it make sense to use the nodes7 library directly?

**Comment by TommyBerz** [comment]
Which library in particular are you thinking about?

**Comment by gfcittolin** [comment]
Either [@st-one-io/nodes7](https://github.com/st-one-io/nodes7), the library that powers this Node-RED node, or [plcpeople/nodeS7](https://github.com/plcpeople/nodeS7), the original one that was the inspiration for the former
